spring.application.name=expense-tracker-backend
//spring.data.mongodb.uri=mongodb+srv://expenseUser:YOUR_Password@expensecluster.3semudu.mongodb.net/expenseDB?retryWrites=true&w=majority
logging.level.root=INFO
logging.level.com.expensetracker.backend=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.data.mongodb.uri=mongodb://localhost:27017/expense_tracker

jwt.secret=mySuperStrongJwtSecretKeyThatIsAtLeast32Chars!



cloudinary.cloud_name=******
cloudinary.api_key= ***********
cloudinary.api_secret=*******