spring.application.name=expense-tracker-backend
spring.data.mongodb.uri=mongodb+srv://expenseUser:Admin1234@expensecluster.3semudu.mongodb.net/expenseDB?retryWrites=true&w=majority
logging.level.root=INFO
logging.level.com.expensetracker.backend=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


jwt.secret=mySuperStrongJwtSecretKeyThatIsAtLeast32Chars!



cloudinary.cloud_name=dq5fio3j5
cloudinary.api_key= 624516687966265
cloudinary.api_secret=SVkF-UjT5bD4i0XNyQBXf3NI0K8